name: robot
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bullet-cpp=3.09=h60cbd38_2
  - ca-certificates=2021.4.13=haa95532_1
  - certifi=2020.12.5=py38haa95532_0
  - cycler=0.10.0=py38_0
  - freetype=2.10.4=hd328e21_0
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.2=254
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.1=py38hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.3=h2bbff1b_0
  - matplotlib=3.4.1=py38haa244fe_0
  - matplotlib-base=3.4.1=py38heae8d8c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.3.0=py38h46781fe_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h2bbff1b_0
  - pillow=8.2.0=py38h4fa10fc_0
  - pip=21.0.1=py38haa95532_0
  - pybullet=3.09=py38h60cbd38_2
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pywinusb=0.4.2=py38h32f6830_2
  - qt=5.9.7=vc14h73c81de_0
  - setuptools=52.0.0=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.35.4=h2bbff1b_0
  - tk=8.6.10=he774522_0
  - tornado=6.1=py38h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - cffi==1.14.5
    - easyhid==0.0.10
    - future==0.18.2
    - hid==1.0.4
    - iso8601==0.1.14
    - opencv-contrib-python==4.5.1.48
    - pycparser==2.20
    - pyyaml==5.4.1
